name: mongodb
base: core22 # the base snap is the execution environment for this snap
version: '5.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: MongoDB in a snap. # 79 char long summary
description: |
  MongoDB is a source-available cross-platform 
  document-oriented database program. Classified 
  as a NoSQL database program, MongoDB uses JSON
  -like documents with optional schemas.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

layout:
  /etc/mongod.conf:
    symlink: $SNAP_COMMON/mongod.conf

package-repositories:
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    url: http://repo.percona.com/psmdb-50/apt
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    url: http://repo.percona.com/percona/apt

apps:
  mongo:
    command: usr/bin/mongo
  mongobridge:
    command: usr/bin/mongobridge
  mongod:
    command: start_mongod.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  mongodump:
    command: usr/bin/mongodump
  mongoexport:
    command: usr/bin/mongoexport
  mongofiles:
    command: usr/bin/mongofiles
  mongoimport:
    command: usr/bin/mongoimport
  mongorestore:
    command: usr/bin/mongorestore
  mongos:
    command: usr/bin/mongos
  mongostat:
    command: usr/bin/mongostat
  mongotop:
    command: usr/bin/mongotop

parts:
  mongo-deb:
    plugin: nil
    stage-packages:
      - percona-server-mongodb
    override-stage: |
      craftctl default
      sed -i "s/fork: true/fork: false/g" $CRAFT_STAGE/etc/mongod.conf
      sed -i "s:/var/log/mongodb/mongod.log:/var/snap/mongodb/common/mongod.log:g" $CRAFT_STAGE/etc/mongod.conf
      sed -i "s:/var/lib/mongodb:/var/snap/mongodb/common/db:g" $CRAFT_STAGE/etc/mongod.conf
      sed -i "s:/var/run/mongod.pid:/var/snap/mongodb/common/mongod.pid:g" $CRAFT_STAGE/etc/mongod.conf
  wrapper:
    plugin: dump
    source: snap/local
