name: charmed-mongodb
base: core22 # the base snap is the execution environment for this snap
version: "5.0" # just for humans, typically '1.2+git' or '1.3.2'
summary: MongoDB in a snap. # 79 char long summary
description: |
  MongoDB is a source-available cross-platform
  document-oriented database program. Classified
  as a NoSQL database program, MongoDB uses JSON
  -like documents with optional schemas.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

website: https://github.com/canonical/charmed-mongodb-snap
contact: https://github.com/canonical/charmed-mongodb-snap/issues/new
issues: https://github.com/canonical/charmed-mongodb-snap/issues/new

system-usernames:
  snap_daemon: shared

hooks:
  install:
    plugs:
      - network
      - network-bind
  configure:
    plugs:
      - network
      - network-bind

package-repositories:
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    url: http://repo.percona.com/psmdb-50/apt
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    url: http://repo.percona.com/percona/apt
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    url: http://repo.percona.com/pbm/apt

slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/var/log/mongod
        - $SNAP_COMMON/var/log/mongos
        - $SNAP_COMMON/var/log/pbm

apps:
  mongo:
    command: drop_priv.sh mongo
    plugs:
      - network
  mongobridge:
    command: drop_priv.sh mongobridge
  mongod:
    command: start-mongod.sh
    daemon: simple
    install-mode: disable
    restart-condition: always
    restart-delay: 20s
    plugs:
      - network
      - network-bind
    slots:
      - logs
  mongodump:
    command: drop_priv.sh mongodump
  mongoexport:
    command: drop_priv.sh mongoexport
  mongofiles:
    command: drop_priv.sh mongofiles
  mongoimport:
    command: drop_priv.sh mongoimport
  mongorestore:
    command: drop_priv.sh mongorestore
  mongos:
    command: drop_priv.sh mongos
    slots:
      - logs
  mongostat:
    command: drop_priv.sh mongostat
  mongotop:
    command: drop_priv.sh mongotop
  mongodb-exporter:
    daemon: simple
    # wrapper is used to run mongodb-exporter as snap_daemon user
    # and pass the URI via `snapctl`.
    command: start-mongodb-exporter.sh
    restart-condition: always
    restart-delay: 20s
    plugs:
      - network
      - network-bind
  pbm:
    # pbm cli uses an environment variable for the URI which is set
    # by `snapctl.` According to the snap docs the recommended way
    # to access thi is via a wrapper script
    command: drop_priv.sh pbm
    plugs:
      - network
      - network-bind
  pbm-agent:
    daemon: simple
    # pbm-agent requires a variable for the mongodb uri,
    # enviornment variables are not available to snap daemons,
    # so they must be passed/loaded via `snapctl`. Handling of
    # this variable is done via a wrapper
    command: start-pbm-agent.sh
    plugs:
      - network
      - network-bind
    slots:
      - logs

parts:
  mongo-deb:
    plugin: nil
    stage-packages:
      - percona-server-mongodb
      - percona-backup-mongodb
      - util-linux
    override-prime: |
      craftctl default
      LICENSE_LOC=usr/share/doc/percona-server-mongodb
      zcat $CRAFT_PRIME/$LICENSE_LOC/LICENSE-Community.txt.gz \
        > $CRAFT_PRIME/licenses/LICENSE-percona-server
    organize:
      usr/share/doc/percona-backup-mongodb/copyright:
        licenses/LICENSE-percona-backup-mongodb
  percona-mongodb-exporter:
    plugin: dump
    source: "https://github.com/percona/mongodb_exporter/releases/download\
      /v0.37.0/mongodb_exporter-0.37.0.linux-64-bit.deb"
  wrapper:
    plugin: dump
    source: snap/local
  snap-license:
    plugin: dump
    source: .
    source-type: local
    stage:
      - licenses/LICENSE-snap
    organize:
      LICENSE: licenses/LICENSE-snap
  percona-mongodb-exporter-license:
    plugin: nil
    build-packages:
      - wget
    override-build: |
      PERCONA_GH=https://raw.githubusercontent.com/percona
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/licenses
      wget ${PERCONA_GH}/mongodb_exporter/v0.37.0/LICENSE \
        -O $CRAFT_PART_INSTALL/licenses/LICENSE-mongodb-exporter
