name: charmed-mongodb
base: core22 # the base snap is the execution environment for this snap
version: '5.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: MongoDB in a snap. # 79 char long summary
description: |
  MongoDB is a source-available cross-platform 
  document-oriented database program. Classified 
  as a NoSQL database program, MongoDB uses JSON
  -like documents with optional schemas.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

system-usernames:
  snap_daemon: shared

layout:
  /etc/mongod.conf:
    symlink: $SNAP_COMMON/mongod.conf

hooks:
    install:
      plugs:
        - network
        - network-bind
    configure:
      plugs:
        - network
        - network-bind

package-repositories:
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    url: http://repo.percona.com/psmdb-50/apt
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    url: http://repo.percona.com/percona/apt
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    url: http://repo.percona.com/pbm/apt

apps:
  mongo:
    command: usr/bin/mongo
  mongobridge:
    command: usr/bin/mongobridge
  mongod:
    command: start-mongod.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  mongodump:
    command: usr/bin/mongodump
  mongoexport:
    command: usr/bin/mongoexport
  mongofiles:
    command: usr/bin/mongofiles
  mongoimport:
    command: usr/bin/mongoimport
  mongorestore:
    command: usr/bin/mongorestore
  mongos:
    command: usr/bin/mongos
  mongostat:
    command: usr/bin/mongostat
  mongotop:
    command: usr/bin/mongotop
  pbm:
    # pbm cli uses an environment variable for the URI which is set by `snapctl.`
    # According to the snap docs the recommended way to access thi is via a wrapper
    # script
    command: start-pbm.sh
    plugs:
      - network
      - network-bind
  pbm-agent:
    daemon: simple
    # pbm-agent requires a variable for the mongodb uri, enviornment variables are not
    # available to snap daemons, so they must be passed/loaded via `snapctl`. Handling
    # of this variable is done via a wrapper
    command: start-pbm-agent.sh
    plugs:
      - network
      - network-bind

parts:
  mongo-deb:
    plugin: nil
    stage-packages:
      - percona-server-mongodb
      - percona-backup-mongodb
      - util-linux
  wrapper:
    plugin: dump
    source: snap/local
