on:
  push:
    branches:
      - "[0-9]/[a-z]+"
      - "8-transition/[a-z]+"
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v41.0.0
    permissions:
      actions: read # Needed for GitHub API call to get workflow version
      contents: read
  publish:
    name: Publish Snap
    needs: build
    uses: canonical/data-platform-workflows/.github/workflows/release_snap.yaml@v41.0.0
    with:
      channel: 8/edge
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      snap-store-token: ${{ secrets.STORE_LOGIN }}
    permissions:
      actions: read # Needed for GitHub API call to get workflow version
      contents: write
