on:
  push:
    branches:
      - '[0-9]/[a-z]+'
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  publish:
    name: Publish Snap
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: mongodb-rock
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: charmed-mongodb_*_amd64.snap
          release: ${{ github.ref_name }}
