#!/bin/bash

set -eux

# Create the necessary parent directories 
mkdir -p "${SNAP_DATA}/etc/pbm/"
mkdir -p "${SNAP_DATA}/etc/mongod/"
mkdir -p "${SNAP_COMMON}/var/lib/mongodb/"
mkdir -p "${SNAP_COMMON}/var/log/mongodb/"

# Copy over the mongod.conf and create needed directories/files
MONGO_CONFIG_FILE="${SNAP_DATA}/etc/mongod/mongod.conf"
echo "configuration file does not exist."
echo "copying default config to ${MONGO_CONFIG_FILE}"
cp -r ${SNAP}/etc/mongod.conf ${MONGO_CONFIG_FILE}


# mongod.conf default values are not consistent with the snap directory system.
sed -i "s/fork: true/fork: false/g" $MONGO_CONFIG_FILE
sed -i "s:/var/log/mongodb:$SNAP_COMMON/var/log/mongodb:g" $MONGO_CONFIG_FILE
sed -i "s:/var/lib/mongodb:$SNAP_COMMON/var/lib/mongodb:g" $MONGO_CONFIG_FILE
sed -i "s:/var/run:/tmp:g" $MONGO_CONFIG_FILE

# Change ownership of snap directories to allow snap_daemon to read/write
chown -R 584788:root "${SNAP_DATA}"/*
chown -R 584788:root "${SNAP_COMMON}"/*
chgrp root "${SNAP_COMMON}/var/log/"*
chmod g+s "${SNAP_COMMON}/var/log/"*
