#!/bin/bash
# Installation hook for charmed-mongodb snap

set -eux

export CONF="${SNAP_DATA}/etc/mongod"
export PBM_CONF="${SNAP_DATA}/etc/pbm/"
export DATA="${SNAP_COMMON}/var/lib/mongodb"
export LOG="${SNAP_COMMON}/var/log/mongodb"

# If the $DATA dir is not there yet, create it
if [ stat -c '%u' "$DATA" == 0 -o ! -d "$DATA" ]; then
    mkdir -p $DATA
    mkdir -p $LOG
    chmod g+s "${LOG}"/*
    chown -R 584788:root "${SNAP_COMMON}"/*
    chgrp root "${LOG}"*
else
    mkdir -p $LOG
    chmod g+s "$LOG"*
    chgrp root "${LOG}"*
fi

# Create the necessary parent directories 
mkdir -p "${PBM_CONF}"
mkdir -p "${CONF}"

# Copy over the mongod.conf and create needed directories/files
MONGO_CONFIG_FILE="${CONF}/mongod.conf"
echo "configuration file does not exist."
echo "copying default config to ${MONGO_CONFIG_FILE}"
cp -r ${SNAP}/etc/mongod.conf ${MONGO_CONFIG_FILE}


# mongod.conf default values are not consistent with the snap directory system.
sed -i "s/fork: true/fork: false/g" $MONGO_CONFIG_FILE
sed -i "s:/var/log/mongodb:$LOG:g" $MONGO_CONFIG_FILE
sed -i "s:/var/lib/mongodb:$DATA:g" $MONGO_CONFIG_FILE
sed -i "s:/var/run:/tmp:g" $MONGO_CONFIG_FILE

# Change ownership of snap directories to allow snap_daemon to read/write
chown -R 584788:root "${SNAP_DATA}"/*
