#!/usr/bin/env bash
# Installation hook for charmed-mongodb snap

set -eux

export CONF="${SNAP_DATA}"/etc/mongod
export PBM_CONF="${SNAP_DATA}"/etc/pbm
export DATA="${SNAP_COMMON}"/var/lib/mongodb
export LOGS="${SNAP_COMMON}"/var/log/mongodb
export MONGO_CONFIG_FILE="${CONF}"/mongod.conf

# Create the necessary parent directories 
mkdir -p $DATA
mkdir -p $LOGS
mkdir -p $PBM_CONF
mkdir -p $CONF

if [ stat -c '%u' "$DATA" == 0 -o ! -d "$DATA" ]; then
    chmod -R 770 "${SNAP_COMMON}"
    chmod 750 "${DATA}"
fi

if [ stat -c '%u' "$LOGS" == 0 -o ! -d "$LOGS" ]; then
    chmod -R 770 "${SNAP_COMMON}"
    chmod g+s "$LOGS"/*
fi

chown -R 584788:root "${SNAP_COMMON}"/*

# Copy over the mongod.conf and create needed directories/files
echo "configuration file does not exist."
echo "copying default config to ${MONGO_CONFIG_FILE}"
cp -r ${SNAP}/etc/mongod.conf ${MONGO_CONFIG_FILE}


# mongod.conf default values are not consistent with the snap directory system.
sed -i "s/fork: true/fork: false/g" $MONGO_CONFIG_FILE
sed -i "s:/var/log/mongodb:$LOGS:g" $MONGO_CONFIG_FILE
sed -i "s:/var/lib/mongodb:$DATA:g" $MONGO_CONFIG_FILE
sed -i "s:/var/run:/tmp:g" $MONGO_CONFIG_FILE

# Change ownership of snap directories to allow snap_daemon to read/write
chown -R 584788:root "${SNAP_DATA}"/*
